In [1]:
import numpy as np

In [2]:
# 1
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2
np.empty((2,2))

array([[5.00e-321, 2.03e-321],
       [5.81e-321, 2.03e-321]])

In [4]:
# 3
y = np.ones((2,2))

In [5]:
# 4
np.array([1,7,9,8,5])

array([1, 7, 9, 8, 5])

In [6]:
# 5 
e = np.empty([3,2], dtype = int)
e

array([[267964128,       576],
       [        0,         0],
       [        1,   5111887]])

In [7]:
# 6
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [8]:
# 7
y.shape

(2, 2)

In [9]:
# 8
y.reshape(1,2,1,2)

array([[[[1., 1.]],

        [[1., 1.]]]])

In [10]:
# 9
y.dtype

dtype('float64')

In [11]:
# 10
r = np.random.randn(10)
r

array([-1.53550719, -0.90978237,  0.39389058, -1.5535655 , -1.40503286,
        0.56951446, -0.947268  ,  1.68288033,  1.69515645, -0.00687255])

In [12]:
# 11
y.ndim

2

In [13]:
# 12
y.size

4

In [14]:
# 13
x.sum()

460

In [15]:
# 14
x.min()

1

In [16]:
# 15
x.max()

91

In [17]:
# 16
i = np.ones((2,2))
i.cumsum(axis=1)

array([[1., 2.],
       [1., 2.]])

In [18]:
# 17
np.exp(x)

array([2.71828183e+00, 5.98741417e+04, 1.31881573e+09, 2.90488497e+13,
       6.39843494e+17, 1.40934908e+22, 3.10429794e+26, 6.83767123e+30,
       1.50609731e+35, 3.31740010e+39])

In [19]:
# 18
np.sqrt(x)

array([1.        , 3.31662479, 4.58257569, 5.56776436, 6.40312424,
       7.14142843, 7.81024968, 8.42614977, 9.        , 9.53939201])

In [20]:
# 19
np.add(i,y)

array([[2., 2.],
       [2., 2.]])

In [21]:
# 20
np.mean(x)

46.0

In [22]:
# 21
np.median(x)

46.0

In [23]:
# 22
np.floor(r)

array([-2., -1.,  0., -2., -2.,  0., -1.,  1.,  1., -1.])

In [24]:
# 23
np.std(r)

1.1936921380371055

In [25]:
# 24
np.abs(r)

array([1.53550719, 0.90978237, 0.39389058, 1.5535655 , 1.40503286,
       0.56951446, 0.947268  , 1.68288033, 1.69515645, 0.00687255])

In [26]:
# 25
i = np.array(([1,2],[3,4]))
i.transpose()

array([[1, 3],
       [2, 4]])

In [27]:
# 26
np.linalg.inv(i)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
# 27
y.itemsize

8

In [29]:
# 28
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [30]:
# 29
for x in np.nditer(i):
   print(x)

1
2
3
4


In [31]:
# 30 
np.sin(i)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [32]:
# 31
np.cos(i)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [33]:
# 32 
np.tan(i)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [34]:
# 33
np.arcsin(np.sin(i))

array([[ 1.        ,  1.14159265],
       [ 0.14159265, -0.85840735]])

In [35]:
# 34
np.arccos(np.cos(i))

array([[1.        , 2.        ],
       [3.        , 2.28318531]])

In [36]:
# 35
np.arctan(np.tan(i))

array([[ 1.        , -1.14159265],
       [-0.14159265,  0.85840735]])

In [37]:
# 36
np.degrees(np.arcsin(np.sin(i)))

array([[ 57.29577951,  65.40844097],
       [  8.11266146, -49.18311805]])

In [38]:
#37 
np.around(np.degrees(np.arcsin(np.sin(i))),2)

array([[ 57.3 ,  65.41],
       [  8.11, -49.18]])

In [39]:
# 38
np.ceil(r)

array([-1., -0.,  1., -1., -1.,  1., -0.,  2.,  2., -0.])

In [40]:
b = np.arange(4, dtype = np.float_).reshape(2,2)
c = np.array(([3,3]))

# 39 
np.add(b,c)

array([[3., 4.],
       [5., 6.]])

In [41]:
# 40
np.subtract(b,c)

array([[-3., -2.],
       [-1.,  0.]])

In [42]:
# 41
np.multiply(b,c)

array([[0., 3.],
       [6., 9.]])

In [43]:
# 42
np.divide(b,c)

array([[0.        , 0.33333333],
       [0.66666667, 1.        ]])

In [44]:
# 43
np.power(c,2)

array([9, 9], dtype=int32)

In [45]:
# 44
np.mod(b,c)  

array([[0., 1.],
       [2., 0.]])

In [46]:
# 45
np.remainder(b,c) 

array([[0., 1.],
       [2., 0.]])

In [47]:
# 46
np.sort(r)

array([-1.5535655 , -1.53550719, -1.40503286, -0.947268  , -0.90978237,
       -0.00687255,  0.39389058,  0.56951446,  1.68288033,  1.69515645])

In [48]:
# 47

dt = np.dtype([('name', 'S10'),('age', int)]) 
students = np.array([("Nouman",38),("Shayan",26),("Moiez", 31), ("Talha",35)], dtype = dt) 

print(np.sort(students, order = 'name'))
print(np.sort(students, order = 'age'))

[(b'Moiez', 31) (b'Nouman', 38) (b'Shayan', 26) (b'Talha', 35)]
[(b'Shayan', 26) (b'Moiez', 31) (b'Talha', 35) (b'Nouman', 38)]


In [49]:
# 48
np.argsort(r)

array([3, 0, 4, 6, 1, 9, 2, 5, 7, 8], dtype=int64)

In [50]:
# 49
np.nonzero(b)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [51]:
# 50
np.where(r > 1)

(array([7, 8], dtype=int64),)